version: '3'
services:
  docs:
    image: ${OKTETO_BUILD_DOCS_IMAGE}
    ports:
    - 8080:8080
endpoints:
  labels:
    dev.okteto.com/endpoints: https://docs-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}/docs
  rules:
    - path: /
      service: docs
      port: 8080