email:

license:

subdomain: 

auth:
  github:
    enabled: true
    clientId: 
    clientSecret:
    organization:

registry:
  storage:
    filesystem:
      enabled: true
      persistence:
        size: 100Gi

buildkit:
  persistence:
    enabled: true
