license:

subdomain: 

cluster:
  endpoint:

buildkit:
  ingress:
    enabled: false
  service:
    type: LoadBalancer

ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb