email: 

license: 

subdomain: 

auth:
  github:
    enabled: true
    clientId: 
    clientSecret:

cluster:
  endpoint:

cloud:
  provider:
    azure:
      enabled: true
      servicePrincipal: ""
      subscriptionID: ""
      tenantID: ""
      resourceGroupName: ""
      storage:
        container: ""
        accountName: ""

buildkit:
  ingress:
    enabled: false
  service:
    type: LoadBalancer